/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 12-Nov-2024 8:37:39 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS "Katastarska_opstina" CASCADE
;

DROP TABLE IF EXISTS "Katastarska_parcela" CASCADE
;

DROP TABLE IF EXISTS "Objekat" CASCADE
;

DROP TABLE IF EXISTS "Politicka_opstina" CASCADE
;

DROP TABLE IF EXISTS "Vlasnik" CASCADE
;

DROP TABLE IF EXISTS "Nacin_koriscenja" CASCADE;
CREATE TYPE Nacin_koriscenja AS ENUM ('Dvoriste','Livada','Njiva','Pasnjak','Suma','Rijeka','Put');


DROP TABLE IF EXISTS "Tip_objekta" CASCADE;
CREATE TYPE Tip_objekta AS ENUM ('Privredni','Stambeni','Javni','Pomocni');


DROP TABLE IF EXISTS "Tip_vlasnika" CASCADE;
CREATE TYPE Tip_vlasnika AS ENUM ('Fizicko_lice','Pravno_lice');

/* Create Tables */

CREATE TABLE "Katastarska_opstina"
(
	id_ko serial NOT NULL,
	naziv_ko varchar(50) NOT NULL,
	povrsina_ko numeric(10,2) NULL,
	geometrija geometry(polygon) NOT NULL,
	id_po integer NOT NULL
)
;

CREATE TABLE "Katastarska_parcela"
(
	id_kp serial NOT NULL,
	broj_kp varchar(50) NOT NULL,
	povrsina_kp numeric(10,2) NULL,
	nacin_koriscenja Nacin_koriscenja NOT NULL,
	geometrija geometry(polygon) NOT NULL,
	id_ko integer NOT NULL
)
;

CREATE TABLE "Objekat"
(
	id_ob serial NOT NULL,
	tip_objekta Tip_objekta NOT NULL,
	povrsina_ob numeric(10,2) NULL,
	geometrija geometry(polygon) NOT NULL,
	id_kp integer NOT NULL
)
;

CREATE TABLE "Politicka_opstina"
(
	id_po serial NOT NULL,
	naziv_po varchar(50) NOT NULL,
	povrsina_po numeric(10,2) NULL,
	geometrija geometry(polygon) NOT NULL
)
;

CREATE TABLE "Vlasnik"
(
	id_vl serial NOT NULL,
	ime_i_prezime varchar(50) NOT NULL,
	"JMBG" bigint NOT NULL,
	adresa varchar(50) NOT NULL,
	tip_vlasnika Tip_vlasnika NOT NULL,
	id_kp integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Katastarska_opstina" ADD CONSTRAINT "PK_Katastarska opstina"
	PRIMARY KEY (id_ko)
;

CREATE INDEX "IXFK_Katastarska opstina_Politicka opstina" ON "Katastarska_opstina" (id_po ASC)
;

ALTER TABLE "Katastarska_parcela" ADD CONSTRAINT "PK_Katastarska parcela"
	PRIMARY KEY (id_kp)
;

CREATE INDEX "IXFK_Katastarska parcela_Katastarska opstina" ON "Katastarska_parcela" (id_ko ASC)
;

ALTER TABLE "Objekat" ADD CONSTRAINT "PK_Objekat"
	PRIMARY KEY (id_ob)
;

CREATE INDEX "IXFK_Objekat_Katastarska_parcela" ON "Objekat" (id_kp ASC)
;

ALTER TABLE "Politicka_opstina" ADD CONSTRAINT "PK_Politicka opstina"
	PRIMARY KEY (id_po)
;

ALTER TABLE "Vlasnik" ADD CONSTRAINT "PK_Vlasnik"
	PRIMARY KEY (id_vl)
;

CREATE INDEX "IXFK_Vlasnik_Katastarska parcela" ON "Vlasnik" (id_kp ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Katastarska_opstina" ADD CONSTRAINT "FK_Katastarska opstina_Politicka opstina"
	FOREIGN KEY (id_po) REFERENCES "Politicka_opstina" (id_po) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Katastarska_parcela" ADD CONSTRAINT "FK_Katastarska parcela_Katastarska opstina"
	FOREIGN KEY (id_ko) REFERENCES "Katastarska_opstina" (id_ko) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Objekat" ADD CONSTRAINT "FK_Objekat_Katastarska_parcela"
	FOREIGN KEY (id_kp) REFERENCES "Katastarska_parcela" (id_kp) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vlasnik" ADD CONSTRAINT "FK_Vlasnik_Katastarska_parcela"
	FOREIGN KEY (id_kp) REFERENCES "Katastarska_parcela" (id_kp) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
ALTER TABLE "Katastarska_opstina"
ALTER COLUMN geometrija TYPE geometry (polygon, 3908);

ALTER TABLE "Katastarska_parcela"
ALTER COLUMN geometrija TYPE geometry (polygon, 3908);

ALTER TABLE "Objekat"
ALTER COLUMN geometrija TYPE geometry (polygon, 3908);

ALTER TABLE "Politicka_opstina"
ALTER COLUMN geometrija TYPE geometry (polygon, 3908);